services:
  bot:
    build:
      target: development
    container_name: discord_bot_dev
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file: ".env.docker"
    image: viet-aus-it/discord_bot:development
    restart: unless-stopped
    volumes:
      - .:/src

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: discord_bot_db
    ports:
      - 5432:5432
    env_file: ".env.docker"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: discord_bot_adminer
    depends_on:
      - db
    ports:
      - 8080:8080
