version: "3.8"

services:
  bot:
    build:
      target: development
    container_name: discord_bot_dev
    image: viet-aus-it/discord_bot:development
    restart: unless-stopped
    volumes:
      - ./discord-bot:/src
      - "/src/node_modules"

  # dashboard:
  #   build:
  #     target: development
  #   container_name: dashboard_dev
  #   image: viet-aus-it/dashboard:development
  #   restart: unless-stopped
  #   volumes:
  #     - ./dashboard:/var/www/
  #     - "/var/www/html"

  db:
    image: postgres
    restart: unless-stopped
    container_name: discord_bot_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
